blog/urls.py
from django.conf.urls import url
from . import views

#namespace
app_name='blog'

urlpatterns = [
	url(r'^$', views.post_list, name='post_list'),
	url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
	url(r'^post/create/$', views.post_create, name='post_create'),
	url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
	url(r'^post/(?P<pk>\d+)/delete/$', views.post_delete, name='post_delete'),
	url(r'^post/draft/$', views.post_draft, name='post_draft'),
	url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
	url(r'^post/category/$', views.category_list, name='post_category'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from portofolio import urls as portofolio_urls
from blog import urls as blog_urls
from . import views as view
#accesing login django



urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),
    url(r'^$', view.home, name='home'),
    #dont include $  in /music if not adding url again
    #like /music/list etc
    url(r'^blog/', include(blog_urls, namespace='blog')),
    url(r'^portofolio/', include(portofolio_urls, namespace='portofolio')),
    #thirdparty
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),   
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

portofolio/urls.py
from django.conf.urls import url
from . import views

app_name='portofolio'

urlpatterns = [
    url(r'^$', views.portofolio_list, name='portofolio_list'),
]

blog/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
#from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
# Create your models here.

def image_location(instance, filename):
	return 'blog/%s/%s' %(instance.id, filename)


class Category(models.Model):
	name = models.CharField(max_length=30)

	def __str__(self):
		return self.name

class Post(models.Model):
	author = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
	title = models.CharField(max_length=50)
	image = models.ImageField(upload_to=image_location,
			null=True, blank=True,
			height_field='height_field',
			width_field='width_field')
	height_field = models.IntegerField(default=0)
	width_field = models.IntegerField(default=0)
	text = RichTextUploadingField('text')
	created_date = models.DateTimeField(default=timezone.now)
	published_date = models.DateTimeField(blank=True, null=True)
	category = models.ForeignKey(Category, verbose_name='Category', null=True, blank=True)

	def publish(self):
		self.published_date= timezone.now()
		self.save()

	def __str__(self):
		return self.title

portofolio/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

def image_location(instance, filename):
	return 'portofolio/%s/%s' %(instance.id, filename)


class Category(models.Model):
	name = models.CharField(max_length=20)

	def __str__(self):
		return self.name

class Technology(models.Model):
	name = models.CharField(max_length=30)

	def __str__(self):
		return self.name

class Post_Portofolio(models.Model):
	title = models.CharField(max_length=30)
	category = models.ForeignKey('Category', on_delete=models.CASCADE)
	image = models.ImageField(upload_to=image_location, 
		height_field='height_field', 
		width_field='width_field',
		null=True, blank=True)
	height_field = models.IntegerField(default=0)
	width_field = models.IntegerField(default=0)
	technology = models.ManyToManyField('Technology')
	description = models.TextField(max_length=500)
	source = models.URLField(max_length=100)
	demo = models.URLField(max_length=100)
	created_date = models.DateTimeField(default=timezone.now, blank=True, null=True)

	def __str__(self):
		return self.title

blog/forms.py
from django import forms
#from pagedown.widgets import PagedownWidget
from .models import Post
from ckeditor_uploader.widgets import CKEditorUploadingWidget


class PostForm(forms.ModelForm):
	text = forms.CharField(widget=CKEditorUploadingWidget())
	#text = forms.CharField(widget=PagedownWidget())
	class Meta:
		model = Post
		fields = ('title', 'image', 'text', 'category')

blog/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from django.utils import timezone
from .forms import PostForm
from .models import Post, Category

# Create your views here.

def home(request):
	return render(request, 'blog/home.html', {})

def category_list(request):
	categories = Category.objects.all()
	return render(request, 'blog/category_list.html', {'categories':categories})


def post_list(request):
	posts_list = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
	categories = Category.objects.all()
	query = request.GET.get('q')
	if query:
		posts_list = posts_list.filter(
					Q(title__icontains=query)|
					Q(text__icontains=query)|
					Q(author__first_name__icontains=query)|
					Q(author__last_name__icontains=query)
					).distinct() # distinct = overriding duplicate items
	paginator = Paginator(posts_list, 5) # Show 25 contacts per page
	page = request.GET.get('page')
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		posts = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		posts = paginator.page(paginator.num_pages)

	context = {
			'posts':posts,
			'categories':categories,
	}

	return render(request, 'blog/post_list.html', context)


def post_detail(request, pk):
	post = get_object_or_404(Post, pk=pk)
	return render(request, 'blog/post_detail.html', {'post':post})

@login_required
def post_create(request):
	if request.method == 'POST':
		form = PostForm(request.POST, request.FILES)
		if form.is_valid():
			post = form.save(commit=False)
			post.author = request.user
			post.save()
			messages.success(request, 'succesfully created')
			return redirect('blog:post_detail', post.pk)
		else:
			messages.error(request, ' not succesfully created')
	else:
		form = PostForm()
	context = {
		'form': form,
	}
	return render(request, 'blog/post_create.html', context)

@login_required
def post_edit(request, pk):
	post = get_object_or_404(Post, pk=pk)
	if request.method == 'POST':
		form = PostForm(request.POST, request.FILES, instance=post)
		if form.is_valid():
			post = form.save(commit=False)
			post.author = request.user
			post.published_date = timezone.now()
			post.save()
			messages.success(request, 'succesfully updated')
			return redirect('blog:post_detail', post.pk)
		else:
			messages.success(request, 'not succesfully created')
	else:
		form = PostForm(instance=post)
	return render(request, 'blog/post_edit.html', {'form':form})

@login_required
def post_delete(request, pk):
	post = get_object_or_404(Post, pk=pk)
	post.delete()
	return redirect('blog:post_list')

@login_required
def post_draft(request):
	posts = Post.objects.filter(published_date__isnull=True).order_by('-created_date')
	return render(request, 'blog/post_draft.html', {'posts':posts})

@login_required
def post_publish(request, pk):
	post = get_object_or_404(Post, pk=pk)
	return redirect('blog:post_detail', post.pk)

mysite/views.py
from django.shortcuts import render


def home(request):
	return render(request, 'blog/home.html', {})

portofolio/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from .models import *

# Create your views here.
def portofolio_list(request):
	instance = Post_Portofolio.objects.filter(created_date__lte=timezone.now()).order_by('-created_date')
	return render(request, 'portofolio/portofolio_list.html', {'instance':instance})

templates/blog/base.html
<!doctype html>
<html class="no-js" lang="en" dir="ltr">
 {% load staticfiles %}

 <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/foundation.css' %}">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" rel="stylesheet">



  <title> Wellcome | Aulia</title>
  {% block head_extra%}
  {% endblock %}
 </head>
 
 <body datawhatinput="mouse">

  {% include 'blog/topbar.html' %}


    <!-- CONTENT -->

   {% block content %}
   {% endblock %}



     <!-- ckeditor -->
     <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
      <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>

    <script src="{% static 'js/vendor/jquery.js' %}"></script>
    <script src="{% static 'js/vendor/what-input.js' %}"></script>
    <script src="{% static 'js/vendor/foundation.js' %}"></script>
    <script src="{% static 'js/app.js' %}"></script>
    <script id="dsq-count-scr" src="//fatkurblog-herokuapp-com.disqus.com/count.js" async></script>
   </body>
</html>

templates/blog/category_list.html
{% extends 'blog/base.html' %}
{% load staticfiles %}


{% block content %}

<ul>
{% for category in categories %}

<li>{{ category }}</li>

{% endfor %}
</ul>

{% endblock %}

templates/blog/footer.html
<!-- footer blog -->
<footer class="bottom">
    <div class="wrap row small-up-1 medium-up-3">
        <div class="column">
         <h4>Contact Info</h4>
         <hr>
         
         <a href=""><span>Phone: 142 132 4321231</span></a>
         <a href=""><span>Email: gushoki@gmail.com</span></a>
         <a href=""><span>Street: 123 bakerstreet 212</span></a>
        </div>
        <div class="column">
         <h4>Site Map</h4>
         <hr>
         <a href=""><span>Blog</span></a>
         <a href=""><span>Portofolio</span></a>
         <a href=""><span>About</span></a>
        </div>
        <div class="column">
        <h4>Social Media</h4>
         <hr>
         <a href="https://web.facebook.com/Rochmancules"><span>Facebook</span></a>
         <a href="https://www.instagram.com/fatkur94/"><span></i>Instagram</span></a>
         <a href="https://twitter.com/fatkur_94"><span></i>Twitter</span></a>
        </div>
    </div>
    <hr>
    <div class="wrap row small-up-1 medium-up-1">
        <div class="column text-center">
        <p>2017-Fatkurblog.com All Right Reversed Designed & Developed by <a href='https://twitter.com/fatkur_94'>Fatkur94</a></p>
        </div>
    </div>

</footer>

templates/blog/home.html
{% extends 'blog/base.html' %}
{% load staticfiles %}

{% block content %}


<div class="hero-section">
  <div class="hero-section-text">
  	<div class="row">
	<h1>Hi I'm Fatkur ;)</h1>
	<br>
    <h3>I build website design with foundation and website application with django</h3>
    <br>
    <br>
    <div class="large-6 large-offset-3 medium-6 medium-offset-3 small-12">
	<div class="button-group-option" data-grouptype="OR">
	  <a href="{% url 'blog:post_list' %}" class="button success">See My blog</a>
	  <a href="{% url 'portofolio:portofolio_list' %}" class="button primary">Portofolio</a>
	</div>

   

    <div id="footer">
    <p>Cover template for <a href="http://foundation.zurb.com">Foundation</a>, by <a href="https://twitter.com/fatkur_94">@fatkur94</a>.</p>
  	</div>

 
 </div>
</div>





{% endblock %}

templates/blog/navbar.html
        <!-- TOP BAR -->
    <div class="top-bar">
      <div class="row">
      <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
          <li class="menu-text">Site Title</li>
          <li>
              <a href="#">One</a>
              <ul class="menu vertical">
                <li><a href="">One</a></li>
                <li><a href="">Two</a></li>
                <li><a href="">Three</a></li>
                <li><a href="">Four</a></li>
                <li><a href="">Five</a></li>
              </ul>
          </li>
          <li><a href="#">Two</a></li>
          <li><a href="#">Three</a></li>
        </ul>
      </div>
      <div class="top-bar-right">
        <ul class="menu">
          <li><input type="search" placeholder="search"></li>
          <li><button type="button" class="button">Search</button></li>
        </ul>

      </div>
      </div>
    </div>

templates/blog/post_create.html
{% extends 'blog/base.html' %}
{% load staticfiles %}

{% block head_extra %}
{{ form.media }}
{% endblock %}

{% block content %}
<section class="main">
<div class="row">
<div class=" columns medium-7 medium-offset-2">
<form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}

{{ form.as_p }}
<button  class="button alert hollow" type="submit"> Save </button>
</form>
</div>
</div>
</section>

{% include 'blog/footer.html' %}

{% endblock %}

templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load staticfiles %}

{% block content %}

  <section class="main">

  {% if messages %}
	<ul class="messages">
    	{% for message in messages %}
    	<li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
    		<div class="callout success">
    			{{ message }}
			</div>
    	</li>
    	{% endfor %}
	</ul>
  {% endif %}


    <div class="row medium-9 large-8 columns">
      <div class="blog-post">      
      	<div class="media-object">
  		    <div class="media-object-section medium-3 small-6 text-center">
              <img class="thumbnail" src= "{% static 'img/aulia.jpg' %}" width="80%">
          </div>
          <div class="media-object-section medium-9 small-6">
            <h4>By Aulia Rahma</h4>
            <hr>
            <p class="hide-for-small-only">I'm going to improvise. Listen, there's something you should know about me... about inception. An idea is like a virus, resilient, highly contagious. The smallest seed of an idea can grow. It can grow to define or destroy you.</p>
            <ul class="menu">
              <li><a href="https://web.facebook.com/Rochmanculess"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
              <li><a href="https://www.instagram.com/?hl=en"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
              <li><a href="https://www.linkedin.com/in/fatkur-rahman-163449129/"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
              <li><a href="https://twitter.com/fatkur_94"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
      <br>
      <br>

      <div class="blog-post">
        <h3 class="post-title">{{ post.title }}</h3>
         <ul class="menu simple text-center post-meta">
              <li><a href="#">Author:{{ post.author.get_full_name }}</a></li>
              <li><a href="{% url 'blog:post_detail' post.pk %}#disqus_thread"></a></li>
              {% if post.published_date %}
					<li>Published:{{ post.published_date|date:"SHORT_DATE_FORMAT" }}</li>
			  {% else %}
					<a href="{% url 'blog:post_publish' post.pk %}" class="hollow button alert">Publish now</a></li>
			  {% endif %}
              <li>Category:{{ post.category }}</span></li>
         </ul>
         <hr>
         {% if user.is_authenticated%}
			<a href="{% url 'blog:post_edit' post.pk %}" class="hollow button warning">Edit</a>
			<a href="{% url 'blog:post_delete' post.pk %}" class="hollow button warning">Delete</a>
		 {% endif %}
        <img src="{% static 'img/django.jpg' %}">
        {% if post.image %}
		<img src='{{ post.image.url }}'>
		{% endif %}
		<p>{{ post.text|safe }}</p>

        <hr>

        <div class="row align-justify">
          <div class="columns medium-6 small-6 tags">
            <span class="alert label"><a href="">tags</a></span>
            <span class="alert label"><a href="">tags</a></span>
            <span class="alert label"><a href="">tags</a></span>
            <span class="alert label"><a href="">tags</a></span>
            <span class="alert label"><a href="">tags</a></span>
            <span class="alert label"><a href="">tags</a></span>
            <span class="alert label"><a href="">tags</a></span>
            <span class="alert label"><a href="">tags</a></span>                
          </div>
        <div class="columns medium-6 small-6 share">
            <span class="social"><a href="https://www.facebook.com/sharer/sharer.php?u=example.org" target="_blank">
                  <i class="fa fa-facebook" aria-hidden="true"></i>
                </a></span>
                <span class="social"><a href="https://twitter.com/intent/tweet">
                  <i class="fa fa-twitter" aria-hidden="true"></i>
                </a></span>
                <span class="social"><a href="">
                  <i class="fa fa-google-plus" aria-hidden="true"></i>
                </a></span>
                <span class="social"><a href="">
                  <i class="fa fa-linkedin" aria-hidden="true"></i>
                </a></span>
          </div>
        </div>

      </div>
      <br>
      <div class="blog-post">
      		<h3 class="text-center">Related Post</h3>
      	<div class='row small-up-1 medium-up-3 text-center'>

      	 <div class="column column-block">
      	  <a href=""><img src="{% static 'img/django.jpg' %}">
      	  <em>This is related post from django</em></a>
      	</div>

      	<div class="column column-block">
      	  <a href=""><img src="{% static 'img/django.jpg' %}">
      	  <em>This is related post from django</em></a>
      	</div>

      	<div class="column column-block">
      	  <a href=""><img src="{% static 'img/django.jpg' %}">
      	  <em>This is related post from django</em></a>
      	</div>

      	</div>

      </div>
      <br>
      <div class="blog-post">
        <div id="disqus_thread"></div>
          <script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
          (function() { // DON'T EDIT BELOW THIS LINE
          var d = document, s = d.createElement('script');
          s.src = 'https://fatkurblog-herokuapp-com.disqus.com/embed.js';
          s.setAttribute('data-timestamp', +new Date());
          (d.head || d.body).appendChild(s);
          })();
          </script>
          <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                                      
      </div>

    </div>


<br>
<br>
<br>


</section>

{% include 'blog/footer.html' %}

{% endblock %}

templates/blog/post_draft.html
{% extends 'blog/base.html' %}
{% load staticfiles %}

{% block content %}

<section class="main">
<div class="row">
<div class="columns medium-7 medium-offset-2">
{% for post in posts %}
<h3><a href="{% url 'blog:post_detail' post.pk %}">{{ post.title}}</a></h3>
<p>{{ post.create_date }}</p>
<p>{{ post.text|safe|truncatechars:200 }}</p>
{% endfor %}
</div>
</div>
</section>

{% include 'blog/footer.html' %}

{% endblock %}

templates/blog/post_edit.html
{% extends 'blog/base.html' %}
{% load staticfiles %}

{% block content %}

<section class="main">
<div class="row">
<div class=" column medium-8 medium-offset-2">
<form method="POST" enctype="multipart/form-data">{% csrf_token %}
{{ form.as_p }}
<input type="submit" name="save" value="Publish" />
</form>
</div>
</div>

</section>

{% include 'blog/footer.html' %}

{% endblock %}

templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% load staticfiles %}

{% block content %}

    <!--  HEADER -->
<section class="main">

    <div class="row" id="content">
      <div class="row column text-center">
        <div class="column-block">
        <img src="{% static 'img/fatkurblog.png'%}" class='logo hide-for-small-only' width="50%">
        <img src="{% static 'img/fatkurblog.png'%}" class='small-logo show-for-small-only' width="100%">
        </div>
      </div>

      <div class="medium-8 columns">

      {% for post in posts %}
        <div class="blog-post">
          <h3 class="post-title"><a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></h3>
            <ul class="menu simple text-center post-meta">
              <li><a href="#">Author: Mike Mikers</a></li>
              <li><a href="{% url 'blog:post_detail' post.pk %}#disqus_thread"></a></li>
              <li>published:{{ post.published_date|date:"SHORT_DATE_FORMAT" }}</li>
              <li>category:{{ post.category }}</span></li>
            </ul>
          <img class="thumbnail" src="{% static 'img/django.jpg' %}">
          <p>{{ post.text|truncatechars:80|safe }}</p>
          <a href="{% url 'blog:post_detail' post.pk %}"><h5 class="read-more">Read More</h5></a>
          <hr>

            <div class="row align-justify">
            <div class="columns medium-6 small-6 tags">
                <span class="alert label"><a href="">tags</a></span>
                <span class="alert label"><a href="">tags</a></span>
                <span class="alert label"><a href="">tags</a></span>
                <span class="alert label"><a href="">tags</a></span>
                <span class="alert label"><a href="">tags</a></span>
                <span class="alert label"><a href="">tags</a></span>
                <span class="alert label"><a href="">tags</a></span>
                <span class="alert label"><a href="">tags</a></span>

            </div>

            <div class="columns medium-6 small-6 share">
                <span class="social"><a href="https://www.facebook.com/sharer/sharer.php?u=example.org" target="_blank">
                  <i class="fa fa-facebook" aria-hidden="true"></i>
                </a></span>
                <span class="social"><a href="https://twitter.com/intent/tweet">
                  <i class="fa fa-twitter" aria-hidden="true"></i>
                </a></span>
                <span class="social"><a href="">
                  <i class="fa fa-google-plus" aria-hidden="true"></i>
                </a></span>
                <span class="social"><a href="">
                  <i class="fa fa-linkedin" aria-hidden="true"></i>
                </a></span>

            </div>
            </div>

          <!-- <div class="callout">

          </div> -->
        </div>
        <br>
        <br>
       {% endfor %}



      </div>
      <div class="medium-4 columns" data-sticky-container>
        {% include 'blog/sidebar.html' %}
        <!-- <div class="sticky" data-sticky data-anchor="content"> -->
          
      </div>
    </div>
    
    <div class="row column text-center">
      <ul class="pagination" role="navigation" aria-label="Pagination">
        {% if posts.has_previous %}
            <li><span class="warning label"><a href="?page={{ posts.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Previous</a></span></li>
        {% else %}
            <li class="disabled">Previous</li>
        {% endif %}

        
        {% if posts.has_next %}
            <li><span class="alert label"><a href="?page={{ posts.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Next</a></span></li>

        {% else %}
            <li class="disabled">Next</li>
        {% endif %}
            <li> Page {{ posts.number }} of {{ posts.paginator.num_pages }}.</li>
      </ul>
    </div>

</section>

{% include 'blog/footer.html' %}

{% endblock %}

templates/blog/topbar.html
<!-- Start of body below -->

<div class="sticky is-stuck" style="width: 100%">
<div class=" responsive-nav-social-mobile" data-responsive-toggle="responsive-nav-social" data-hide-for="medium">
  <div class="responsive-nav-social-mobile-left ">
    <ul class="menu">
      {% if user.is_authenticated %}
          <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i></a></li>
          {% else %}
          <li><a href="{% url 'login' %}"><i class="fa fa-sign-in" aria-hidden="true"></i></a></li>
          {% endif %}
      <li><a href="https://web.facebook.com/Rochmancules"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
      <li><a href="https://www.instagram.com/fatkur94/"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
      <li><a href="https://www.linkedin.com/in/fatkur-rahman-163449129/"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
      <li><a href="https://twitter.com/fatkur_94"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
    </ul>
  </div>
  <div class="responsive-nav-social-mobile-right">
    <button class="menu-icon" type="button" data-toggle="responsive-nav-social"></button>
  </div>
</div>





<div data-sticky-container>
  <div class="responsive-nav-social top-bar" id="responsive-nav-social" data-sticky data-options="marginTop:0;">
    <div class="row align-justify align-middle" id="responsive-menu">
      <div class="top-bar-left">
        <ul class="menu vertical medium-horizontal menu-hover-lines">
          <li><a href="{% url 'home' %}"><strong>HOME</strong></a></li>
          <li><a href="{% url 'blog:post_list' %}"><strong>BLOG</strong></a></li>
          <li><a href="{% url 'portofolio:portofolio_list' %}"><strong>PORTOFOLIO</strong></a></li>
          <li><a href="#"><strong>ABOUT</strong></a></li>
          <li><a href="#"><strong>CONTACT</strong></a></li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'blog:post_create' %}"><strong>Create</strong></a></li>
          <li><a href="{% url 'blog:post_draft' %}"><strong>Draft</strong></a></li>
          {% endif %}
          
        </ul>
      </div>
      <div class="responsive-nav-social-right top-bar-right hide-for-small-only">
        <ul class="menu">
          <li><a href="https://web.facebook.com/Rochmancules"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
          <li><a href="https://www.instagram.com/fatkur94/"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
          <li><a href="https://www.linkedin.com/in/fatkur-rahman-163449129/"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
          <li><a href="https://twitter.com/fatkur_94"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i></a></li>
          {% else %}
          <li><a href="{% url 'login' %}"><i class="fa fa-sign-in" aria-hidden="true"></i></a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  </div>
</div>

</div>